### ISSUE TITLE
how do I get the project to run in visual studio?

### ISSUE THREAD

**Issue by smwentum** [sys27/xFunc#103]
Hi i wanted to help out, but when i open the project and hit build i keep getting errors. like for example on line 278 https://github.com/sys27/xFunc/blob/master/xFunc/Views/MainView.xaml.cs the compiler is complaining  about the $.

**Comment by sys27** [comment]
Sorry, but you need to install Visual Studio 2015. '$' is a part of C# 6 and you need new version of compilers. Maybe, some how, you can connect new compilers to Visual Studio 2013.
