### ISSUE TITLE
Support Complex Numbers

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#147]
Hi Dmitry,

it would be really great to support complex numbers.
Maybe it would be a good idea to integrate the System.Numerics.Complex-Datatype.
The type already brings the most features. It would be nice to parse a expression
with a komplex number 'i' or a degree value '35°'. Like to support sqrt(-1).

Thanks for my mention ;)
I've already seen that you have added the nabbla-operator. great.

Kind regards
Ronny

**Comment by ronnycsharp** [comment]
this could be a solution.

var exp = Parse("5+10i") -> ComplexExpression : IExpression
Functions: 
// Re(exp) => 5
// Im(exp) => 10
// Abs(exp) => sqrt(5^2+10^2) -> Complex.Abs(..)

// 5+10i
var complex1 = new Complex(5, 10);

Trigonometrical-Functions like sin could easy calculated like this

public class Sin : TrigonometricExpression {
    Sin(IExpression arg){}
    IExpression CalculateRadians(paramerts) {
        if ( arg is ComplexExpression ) {
            return new ComplexExpression(Complex.Sin((ComplexExpression)arg).complexNumber));
        } else ...
    }
}

**Comment by sys27** [comment]
Hi.

Good suggestion. I should think about it.
Maybe I will try to implement this in the one of next release.

- Add support to lexer.
- Add new expression.
- Add new result type.
- Add support of all function from System.Numerics.Complex (like sin, cos, log, +, - and etc).
  - Add function to return the real part, the imaginary part, magnitude and phase.
  - Update existing expression to support complex (based on result type of argument).
  - etc.
- Add tests (usual complex numbers, combination of real and complex numbers, etc.).

Thank you.

**Comment by ronnycsharp** [comment]
Great. =) thx

**Comment by ronnycsharp** [comment]
Hi Dimitry,
I've seen the changes you have been made to the Complex-Branch. It looks good.
I can't wait to parse my first complex expression :)
If you want to support the full range of trigonometrical functions like acot, acsc etc. you can use this helper-class. It would be nice, if you could support expressions like this, '10+35°'.

https://gist.github.com/cab1729/3152625

Kind regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp Hi,

I will support all types of trigonometrical and reverse functions, but right now, I have to complete work with lexer (it's not ready, you cannot parse complex expressions), then I will try to implement trig functions and '10+35°'.

**Comment by sys27** [comment]
Add UI for complex numbers.

**Comment by sys27** [comment]
Override ToString function of Complex Number to format data like '{0} + {1}i'.

**Comment by sys27** [comment]
Replace "magnitude" to "abs".

**Comment by ronnycsharp** [comment]
Hi, I am working with complex functions and it looks good, 
but some thing that I miss here is the complex result of a negative argument in a square root, for example, sqrt(-1) should be an complex result with "i". Or i^2 should be -1. 
Maybe it's hard to implement these checks. But we could start with a simple test for negative arguments in square root.

Kind regards
Ronny ;)

**Comment by sys27** [comment]
@ronnycsharp 
Hi, thx for comment.

I think _sqrt(-9)_ can be simple implemented in _Sqrt.cs_ by adding new logic for negative numbers.
_i^2_ is not so easy. _i_ can be just a variable, which equals to -1, but it won't work, because -1^2 = 1.

**Comment by sys27** [comment]
Also, complex numbers have bug.

Parse:
3+0i => 30i
3-0i => 30i
ToString method doesn't add a sign.

**Comment by sys27** [comment]
We should update lexer to support only 'i' as complex number. It will solve i^2.

**Comment by ronnycsharp** [comment]
Do you have seen my comment on you commit?
About pow and root, which should also be supported with a complex argument.
It would be very nice to have a flag to allow complex operations and complex result values.
With complex-flag enabled, sqrt(-1) should return i and with disabled flag it should return NaN.
In my graphical calculator from Texas Instruments, it's solved by a special complex operation mode.

Kind regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
Yep, I saw it. I will think about a flag.

**Comment by sys27** [comment]
@ronnycsharp 
I think I can add flag to ExpressionParameters class (like Angles), but I'm not sure, because we should respect this flag in all places (it's possible to forgot to check this flag).

**Comment by sys27** [comment]
@ronnycsharp 
I think I won't implement a flag for complex numbers, because it's useful only for ```Sqrt``` and I don't understand why do we need to return ```NaN``` for ```sqrt(-9)```. Also, if we implement it in ```ExpressionParameter```, then it's not clear, what about other operation like ```Add```, should we disable complex number there. Also, if we add flag to disable complex numbers in lexer, what about expression created from code (like ```new Add(new ComplexNumber(...), new ComplexNumber(...))```), in such case we have to completely disable complex numbers.

So, right now I think I will skip it.
If user require such logic, he can create custom ```Sqrt``` expression by extending ```Lexer```, ```ExpressionFactory```.

**Comment by ronnycsharp** [comment]
Hi Dmitry,
I saw your changes. great. It's nice to have a modulo-operator.
With the complex-flag, you're right. We should not add such a feature, only for sqrt. 

One other thing, do you mean it's possible to build a indefinite integral from a function, 
like f(x)=2*cos(x) => F(x)=2*sin(x)+C. 

Kind regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
Hi, infinite integral is not so easy as derivative, because derivative has transformation table and strict rules, when infinite integral doesn't. There is no rule for division. We have to implement integration by parts/substitution or solving of equation.
Maybe I missed something, if you have any good idea, please share.

**Comment by sys27** [comment]
@ronnycsharp 
Possible we can use [Risch algorithm](https://en.wikipedia.org/wiki/Risch_algorithm)

**Comment by ronnycsharp** [comment]
Cool, sounds good.
Other thing. At the Moment I am working with complex numbers,
and I've seen that some results are different from other calculators, like wolfram alpha.
For example, 5+10i*3 gave me the result = 15+30i, but on wolfram it is 5+30i, maybe there 
is some issue with priority. 

Regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
I think it is not an issue. Wolfram uses usual math priority: _mul_ is higher than _add_ (no matter which operand do you use). So, Wolfram understands only _10i_ as complex number, then Wolfram will _mul_ it by 3 and then add 5. But xFunc tries to parse 'full' complex number (5 + 10i, with both parts) and only then multiply it.

**Comment by sys27** [comment]
@ronnycsharp 
Possible, Wolfram use only _i_ as complex number and than parse it like:
i => 10 * i => 0 + 10i => 0 + 10i * 3 => 0 + 30i => 5 + 0 + 30i => 5 + 30i.

Right now, I don't know which approach is right. Wolfram's approach is more simple (xFunc has more complicated logic). Wolfram use only _i_ symbol as indicator of complex number.

**Comment by sys27** [comment]
I have implemented same logic as in wolfram.

**Comment by sys27** [comment]
Add lexer tests for complex number (with '°' symbol).

**Comment by ronnycsharp** [comment]
Hi,
one thing I miss here is the following symbol.
r = absolute value of complex number
θ = phase (for example. 20°)
f(x) = r ∠ θ

Normally we can't enter a polar equation without this symbol (∠).
http://www.intmath.com/complex-numbers/4-polar-form.php

Regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
Right now, We have similar syntax: 10+35° (r + θ, we are just using '+' sign instead of '∠') and I think it's easier to type plus sign, but I can try to add 'right' syntax.

**Comment by ronnycsharp** [comment]
It would be great to have the right syntax. =)

**Comment by sys27** [comment]
done

**Comment by ronnycsharp** [comment]
perfect! ;) thx
