### ISSUE TITLE
Support Modulo-Operator

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#153]
Hi,

complex-numbers works quite nice. 
It would also be nice to support a %-Operator and mod-function.
Like 25%7=4, mod(25,7)=4.  Maybe I can implement it.

I've implemented the definite-integral,
If you want to support it. You can look into my code.

https://github.com/ronnycsharp/xFunc/blob/complex/xFunc.Maths/Expressions/DefiniteIntegral.cs

Another change, 
I have modified the abs-Function, to support vectors.

https://github.com/ronnycsharp/xFunc/blob/complex/xFunc.Maths/Expressions/Abs.cs

The code is untested, I've merged it into the new version with your new Execution-Method.

Regards
Ronny

**Comment by sys27** [comment]
I will think about it later, after complete work on complex numbers.

**Comment by sys27** [comment]
The priority of % should be higher than +, - and etc.
