### ISSUE TITLE
Solve-Function

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#154]
Hi Dimitry,

I will add a few nice to have features here.
Maybe we can implement it together.

For example a simple linear equation solver.
Like 2x+4=12, or a 2x^2+4=12, x= ...

Regards
Ronny

**Comment by sys27** [comment]
Duplicate of #39.

**Comment by sys27** [comment]
Right now, the priority is to complex the work on complex number and fix existing bugs.

Also, I don't know a good solution for it (to support any kind of equation at the same time).
