### ISSUE TITLE
Cross-Operator for Vectors

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#158]
Hi Dimitry,

I have another good idea of a feature.
Calculate the cross product of two vectors with the cross operator V1 x V2.
The System.Numerics-Assembly can be used for this. For Example Vector3.Cross(..).

Kind regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
Hello.

We can try to implement this function, but we should create custom logic, because vector of xFunc is not limited by 3 values.

**Comment by ronnycsharp** [comment]
I've seen that the cross product makes no sense with vectors of 4, or 5 components etc.
Perhaps we should ignore the others components of the given vector if it has more as 3 components.
There is one exception, with vectors of 7. But, perhaps we should ignore this.
By this way, we could use the existing Cross-Function.

**Comment by sys27** [comment]
@ronnycsharp 
I'm not sure. But I think throwing of exception is better (if vector size != 3).

**Comment by ronnycsharp** [comment]
yes, it should be the better solution for this.

**Comment by sys27** [comment]
We have small problem _Vector3_ was added in .Net 4.5+.
_System.Numerics_ contains only two types: _BigInteger_ and _Complex_.
