### ISSUE TITLE
Add support of × and − symbols

### ISSUE THREAD

**Issue by sys27** [sys27/xFunc#172]
5 + ((1 + 2) × 4) − 3

**Comment by ronnycsharp** [comment]
Hi Dmitry,
perhaps it's better to use the x-character for vector-cross operation.
v1 x v2 = v3. 

Regards
Ronny

**Comment by sys27** [comment]
I think I will keep * and x the same, because in any case it will be parsed into _Mul_ expression object (we just need to add support of multiplication (cross operator) of vectors).

**Comment by ronnycsharp** [comment]
Hi Dminitry,
it would be really cool to use this unicode for the vector cross product, 
U+2A2F, it's the officially unicode sign for such an operation.

So we could parse v1 ⨯ v2, I know it looks like the multiplication sign, but
it's only needed for the parser to differentiate between the operations.

http://www.fileformat.info/info/unicode/char/2a2f/index.htm

Best regards
Ronny
