### ISSUE TITLE
Support Fractions

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#175]
Hi Dmitry,
I have another good idea, what do you think about fraction-support.
Like 2 1/2  => 2,5.

Maybe with conversion of a decimal-number into a fractionalized number.

Regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
Hi.

How do we understand that '2 1/2' is equal to '2.5' instead of '21/2 = 10.5'?

Also, right now, you can use the following expression: 2 + 1/2 = 2.5.

**Comment by ronnycsharp** [comment]
Perhaps it can be parsed like this: frac(2,1,2*x) =>2+(1/(2*x)) with a Fraction-Expression.

**Comment by ronnycsharp** [comment]
![img_0010](https://cloud.githubusercontent.com/assets/1917475/21683878/8ef40a2e-d35b-11e6-9b6a-9b568464187a.PNG)

Hi Dmitry, That's what I mean.
It would be nice to enter a decimal number with an additional fraction part.

Regards
Ronny
