### ISSUE TITLE
Can't parse a spherical expression with current dev-branch

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#184]
Hi Dmitry,

today,  I am working with your current dev-branch and a run into some problems.
The most of them, I could fix with a few backward-compatibility methods and properties.
But I can't parse this expression anymore ("5*cos(4*φ)"). It raises an exception ... "The symbol '*φ' is not supported.". I use this symbol as variable like x or y.

Regards
Ronny

**Comment by sys27** [comment]
Hi.

This issue is introduced by implementing new lexer logic (regex expression). I forgot to include greek letters to the pattern.

Thanks.
