### ISSUE TITLE
Sum-Function doesn't work correctly

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#188]
Hi Dmitry,

something is wrong with sum.
I tried to parse a sum from 0 to 10 with body and inc of 1.

var proc = new Processor ();
var exp = proc.Parse ("sum(1,0,10,1,n)");
var parameters = new ExpressionParameters (AngleMeasurement.Radian);
parameters.Variables.Add (new xFunc.Maths.Expressions.Collections.Parameter ("n", 0));
var result = exp.Execute (parameters);

The result should be 11, but was 12.

I've also seen that the execute-method now needs a mandatory ExpressionParameters-Object, 
but it shouldn't, because the n-variable is only used internally from sum.

Maybe you know whats wrong.
Kind regards
Ronny

**Comment by sys27** [comment]
Hi @ronnycsharp 
The 'Sum'/'Product' function was reworked in 3.2.0 version (see #165), the main reason is that these function is too similar to common for loop. So, right sum function adds all argument to one value, eg. 
`sum(5, 8, 11, 32) = 56`

**Comment by ronnycsharp** [comment]
Thanks. Now, I have to use the for-expression.
