### ISSUE TITLE
phase/arg of complex number ignores measurement

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#191]
Hi Dmitry,

the phase-function which uses System.Numerics.Complex.Phase - Property already returns a radian angle and ignores the measurement of the given ExpressionParameters-Object.

phase(5∠20°) should return 20.0 but returns 1.15

Regards
Ronny

**Comment by ronnycsharp** [comment]
`
 // Code from System.Numerics.Complex
public static Complex FromPolarCoordinates(Double magnitude, Double phase) {
    return new Complex((magnitude * Math.Cos(phase)), (magnitude * Math.Sin(phase)));
}
`

from Lexer:
`
tokens.Add(new ComplexNumberToken(Complex.FromPolarCoordinates(magnitude, phase)));
`

Parsing "5∠20°" uses Complex.FromPolarCoordinates, but this Factory-Method needs a radian.

**Comment by sys27** [comment]
Right now, I'm not sure about fix, because the 'FromPolarCoordinates' function is invoked in lexer, but ExpressionParameters object is used on 'Execute'-time.

**Comment by ronnycsharp** [comment]
I've solved it in my fork.

**Comment by sys27** [comment]
Oh, I understand, AngleMeasurement will affect only the 'Phase' function (it fill convert to specified measurement), but '5∠20°' expression will always be parse as Degrees (not Radians).

**Comment by ronnycsharp** [comment]
'5∠20°' should always be parsed as a degree value. But I am not sure. The arg-function should return as deg, rad or grad, in relation to the measurement.
