### ISSUE TITLE
Support for exponential form of a complex number 

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#192]
Hi Dmitry,

maybe it's hard to implement, but it would be nice to have.
=> example: ..Tokenize("r * e^(i * phi)");

when we find an 'i' character in an exponent of the base 'e', then we can build a complex number from polar coordinates.

Perhaps you could think about it. =)

Best regards
Ronny

**Comment by sys27** [comment]
Possible, but I think that such logic is related to Lexer. I think we should add some 'semantic' analyzer (as a part of parsing process, which will convert _e^i_ to Complex number). Maybe, it will useful for #119.

**Comment by ronnycsharp** [comment]
sounds good.
