### ISSUE TITLE
The 'Root' expression should support ComplexNumber

### ISSUE THREAD

**Issue by sys27** [sys27/xFunc#199]
The 'Root' expression should support ComplexNumber as Sqrt.

eg. root(-16, 4)

**Comment by ronnycsharp** [comment]
Hi Dmitry,
there is still some issue in your dev-branch.
The root-function doesn't give me the right result.
I tried it with the 5th root of x.

https://www.wolframalpha.com/input/?i=5th+root+of+x

Regards
Ronny
