### ISSUE TITLE
Support for Vector-Dot-Product

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#203]
Hi Dmitry,

it would be nice to have a dot product of two vectors like {{1, 2}*{3, 4}}.
The result should be 10. It isn't executable at the moment.

Regards
Ronny

**Comment by sys27** [comment]
This issue will affect #158, the 'cross product' function will be extracted to separate function or operator (eg. ×), and default action for multiplication of vectors (vector * vector) will be dot product (scalar product).

**Comment by ronnycsharp** [comment]
great ;)
