### ISSUE TITLE
LaTeX support.

### ISSUE THREAD

**Issue by sys27** [sys27/xFunc#76]
We should implement new lexer.

**Comment by sys27** [comment]
Add LaTeXFormatter to support converting of expressions to string (see #166).

**Comment by ronnycsharp** [comment]
Hey Dmitry,

maybe it would be useful to create an expression-object from a latex-formatted string.
By this way, we could implement some nice features, like expression scanning.
I've seen there is a nice app named MathPix, which has a free to use backend-service (until 3000reqs/month) for converting scanned math-formulas to latex. I've checked this, and it'
great.

Best regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
This issue is about both approaches: parse LaTeX string to expression tree and convert expression tree to LaTeX string.

It's not so hard to implement, just need some time.

**Comment by sys27** [comment]
Won't do.
