### ISSUE TITLE
Laplace and Nabla-Operator

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#83]
Hey Dmitry,

what do you think about these operators? Do you know it?
In my study I now have these operators. It would be very nice to have such operators in the library.
The result of the nabla-operator is a vector with partial differentiations of x,y and z.

like this-> nabla("2x+y^2+z") the result is {2,2y,1}.

Laplace is simular.
Regards
Ronny

**Comment by ronnycsharp** [comment]
I've seen you have been implemented the nabla-operator, what do you think about laplace-operator. 
It's also a differential operator.

https://en.wikipedia.org/wiki/Laplace_operator

Regards
Ronny

**Comment by sys27** [comment]
@ronnycsharp 
Is the same as del operation, just second derivative?

del("2x+y^2+z") => {2,2y,1}
laplace("2x+y^2+z") => {0, 2, 0}

Am I right?
